In [3]:
import numpy as np

a = np.array([[1,2,3]])
# print(a)

b = np.array([[1,2,3],[4,5,6]])
# print(b)

c = np.array(b * 2)
print(c)
print(type(c))

[[ 2  4  6]
 [ 8 10 12]]
<class 'numpy.ndarray'>


In [17]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [18]:
arr = np.array([10, 20, 30, 40])

print(arr.ndim)    # Number of dimensions
print(arr.shape)   # (rows, columns)
print(arr.size)    # Total elements
print(arr.dtype)   # Data type

1
(4,)
4
int64


In [19]:
a = np.zeros((3,4))

print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
a = np.ones(4)
b = np.ones((3,2))

print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
random_arr = np.random.rand(1,3)
print(random_arr)

[[0.242431   0.67727335 0.36123566]]


In [30]:
ran_arr = np.random.randint(1,100, size=5)
ran_arr1 = np.random.randint(1,100, size=(2,3))
print(ran_arr)
print(ran_arr1)

[64 22 21 64 77]
[[88  9 26]
 [87 92 58]]


In [38]:
# ran = np.random.randint(1,50, size=(4,4))
mat = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

# print(ran)
# print(ran[0:1, 0:2])
print(mat[2:, 2:])

[[11 12]
 [15 16]]


In [ ]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# print(arr1 + arr2)
# print(arr1 - arr2)
# print(arr1 / arr2)
# print(arr1 % arr2)
# print(arr1 * arr2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [7]:
arr = np.array([1,2,3,4])
# print(arr.sum())
print(arr.mean())
# print(arr.max())
# print(arr.min())

2.5


In [48]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr = np.random.randint(10, 100, 10)
print(arr)

[48 31 12 72 67 55 94 79 65 10]


In [50]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [53]:
# arr_fil = np.array([1,2,3,4,5,6])

# a = arr_fil  > 2
# print(a)

arr = np.array([10, 25, 30, 5, 40])

mask = arr > 20
print(mask)

[False  True  True False  True]


In [ ]:
nums = [1, 2, 3, 4]

# squared = list(map(lambda n: n*n, nums))
# print(squared)

a = list(map(lambda i: i+1, nums))
print(a)

[2, 3, 4, 5]


In [61]:
nums = [1,2,3,4,5]

fil = list(filter(lambda i: i > 2, nums))

print(fil)

[3, 4, 5]


In [ ]:
# import reduce from functools # Will not work
from functools import reduce

arr_red = [1,2,3,4,5,6]
red = reduce(lambda x,y: x + y, arr_red)
print(red)

# nums = [1, 2, 3, 4]
# result = reduce(lambda a, b: a + b, nums)
# print(result)


21


In [ ]:
a = np.array([1,2,3,4,5])

# b = a.view()

# # print(b[0])
# b[0] = 10
# print(a)
# print(b)

# a[0] = 100
# print(a)

c = a.copy()
c[1] = 999

print(a)
print(c)

[1 2 3 4 5]
[  1 999   3   4   5]


In [71]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
arr = np.array([10,20,30,40,50,60])

new_arr = np.array_split(arr, 3)
print(new_arr)

[array([10, 20]), array([30, 40]), array([50]), array([60])]


In [74]:
arr = np.array([40, 10, 30, 20])

print(np.sort(arr))
print(np.argmax(arr))  # Index of max value

[10 20 30 40]
0


In [75]:
matrix = np.array([
    [3, 2, 1],
    [6, 5, 4]
])

print(np.sort(matrix))

[[1 2 3]
 [4 5 6]]


In [77]:
arr = np.array([10,20,30,40])

x = np.where(arr == 20)
print(x)

(array([1]),)


In [78]:
arr = np.array([0, 30, 45, 60, 90])

print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr+1))   # +1 to avoid log(0)

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[0.         3.4339872  3.8286414  4.11087386 4.51085951]


In [79]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(np.sum(matrix, axis=0))  # Column-wise
print(np.sum(matrix, axis=1))  # Row-wise

[5 7 9]
[ 6 15]


In [80]:
arr = np.array([10,20,30,40,50])

print(arr[[0, 2, 4]])

[10 30 50]


In [81]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a, b))

32


In [85]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# print(A)
# print(B)
print(np.matmul(A, B))
print(A @ B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [9]:
I = np.eye(5)
# I = np.eye(5,7)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
M = np.array([[1,2,3],
              [4,5,6]])

# print(M.T)
print(M.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
M = np.array([
            [4,7],
            [2,6]
            ])

inv_M = np.linalg.inv(M)
print(inv_M)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [8]:
M = np.array([[2,1],
              [1,2]])

print(np.linalg.det(M))       # Determinant
print(np.linalg.eig(M))       # Eigen values & vectors

2.9999999999999996
EigResult(eigenvalues=array([3., 1.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))


In [9]:
data = np.array([
    [101, 85, 90],
    [102, 78, 88],
    [103, 92, 95]
])

roll_no = data[:, 0]
marks = data[:, 1:]

print("Roll:", roll_no)
print("Marks:\n", marks)

Roll: [101 102 103]
Marks:
 [[85 90]
 [78 88]
 [92 95]]


In [10]:
import numpy as np

data = np.array([
    [101, 85, 90, 88],
    [102, 78, 82, 80],
    [103, 92, 95, 94],
    [104, 70, 75, 72],
    [105, 88, 91, 89]
])

roll = data[:, 0]
marks = data[:, 1:]

avg = np.mean(marks, axis=1)
topper_index = np.argmax(avg)

print("Average Marks:", avg)
print("Topper Roll No:", roll[topper_index])


Average Marks: [87.66666667 80.         93.66666667 72.33333333 89.33333333]
Topper Roll No: 103


In [ ]:
import pandas as pd

df = pd.read_csv("students.csv")
print(df)

  xcaxzczxczxczxczxczxczxczx
0           Anuarg \sdmas;ld
1                  s;lmclsxz
2      d;leomfcmSDFOMDSCLMSD
3                       LMD;


In [12]:
df = pd.read_json("students.json")
print(df)

   roll   name  marks
0   101  Rahul     85
1   102   Aman     78


In [13]:
import json

with open("students.json", "r") as file:
    data = json.load(file)

print(data)


[{'roll': 101, 'name': 'Rahul', 'marks': 85}, {'roll': 102, 'name': 'Aman', 'marks': 78}]


In [28]:
import pandas as pd

data = {
    "name": [" Rahul", "Aman", "Priya", None, "Aman"],
    "marks": [85, None, 95, 78, 85]
}

df = pd.DataFrame(data)
print(df)
print('\n')
# df.dropna(inplace=True)
# df["marks"].fillna(df["marks"].mean(), inplace=True)
# df.drop_duplicates(inplace=True)
# df["name"] = df["name"].str.strip()
# df.dropna(inplace=True)
# print(df)

df.fillna(0, inplace=True)
print(df)

     name  marks
0   Rahul   85.0
1    Aman    NaN
2   Priya   95.0
3    None   78.0
4    Aman   85.0


     name  marks
0   Rahul   85.0
1    Aman    0.0
2   Priya   95.0
3       0   78.0
4    Aman   85.0
